export const columns = [
    {
      field: "ID",
      headerName: "ID",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "RegisterID",
      headerName: "RegisterID",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "Name",
      headerName: "Name ",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "Age",
      headerName: "Age",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "Phone",
      headerName: "Phone",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "Email",
      headerName: "Email",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
  
    {
      field: "Address",
      headerName: "Address",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
    {
      field: "City",
      headerName: "City",
      flex: 1,
      align: "center",
      headerAlign: "center",
    },
  ];
  export const rows = [
    {
      id: 1,
      ID: "1",
      RegisterID: Math.floor(Math.random() * 1001),
      Name: "Abdulrahman",
      Age: "28",
      Phone: "01006431531",
      Email: "abdomossad670@ReportGmailerrorred.com",
      Address: "zifta-gharbia",
      City: "Egypt",
    },
    {
      id: 2,
      ID: "2",
      RegisterID: Math.floor(Math.random() * 1001),
      Name: "Mosad",
      Age: "28",
      Phone: "01006431815",
      Email: "abdomossad670@gmail.com",
      Address: "zifta-gharbia",
      City: "Egypt",
    },
    {
      id: 3,
      ID: "3",
      RegisterID: Math.floor(Math.random() * 1001),
      Name: "Ahmed",
      Age: "27",
      Phone: "01551193040",
      Email: "abdomossad670@ReportGmailerrorred.com",
      Address: "zifta-gharbia",
      City: "Egypt",
    },
    {
      id: 4,
      ID: "4",
      RegisterID: Math.floor(Math.random() * 1001),
      Name: "Ahmed",
      Age: "27",
      Phone: "01551193040",
      Address: "zifta-gharbia",
      Email: "ahmedmossad670@gmail.com",
      City: "Egypt",
    },
    {
      id: 5,
      ID: "5",
      RegisterID: Math.floor(Math.random() * 1001),
      Name: "mahmoud",
      Age: "26",
      Phone: "01551193040",
      Address: "zifta-gharbia",
      Email: "mahmoudmossad670@gmail.com",
      City: "Egypt",
    },
    {
      id: 6,
      ID: "6",
      RegisterID: Math.floor(Math.random() * 1001),
      Name: "mohamed",
      Age: "28",
      Phone: "01551193040",
      Address: "zifta-gharbia",
      Email: "mohamedmossad670@gmail.com",
      City: "Egypt",
    },
    {
      id: 7,
      ID: "7",
      RegisterID: Math.floor(Math.random() * 1001),
      Name: "ali",
      Age: "28",
      Phone: "01551193040",
      Address: "zifta-gharbia",
      Email: "alimossad670@gmail.com",
      City: "Egypt",
    },
  ];
  